server:
  port: 9292

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER
          uri: lb://USER
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT
          uri: lb://DEPARTMENT
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT
                fallbackuri: forward:/departmentServiceFallBack

#if my service take the 5 seconds then out fallback controller will be hit
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  intance:
    hostname: localhost