server:
  port: 7860

spring:
  application:
    name: HYSTRIX-DASH

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  intance:
    hostname: localhost
